### ISSUE TITLE
FacilityManagerExtension Backend

### ISSUE THREAD

**Issue by mawiegand** [mawiegand/velpesued#6]
Create FacilityManagerExtension Backend.

![klassendiagramm](https://user-images.githubusercontent.com/2320926/43487244-9565afa8-9505-11e8-94f2-c89ac77dcd1d.jpeg)

**Comment by mawiegand** [comment]
Moving timeslot feature (#18) to next release cause it's not important and only **nice to have**.
So should be ready for first release.

@lhannigbrinck please check if nothing is missing and everything works as expected. :smiley:

**Comment by SStalker** [comment]
I tested most of the functionality except timeslots and it worked as expected.

**Comment by mawiegand** [comment]
> I tested most of the functionality except timeslots and it worked as expected.

Thanks!
